# Workflow megnevezés
name: CI - Build and Push Docker image

#minden main brach-ra push -nál, atomatikusan a pipeline
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

#Pipeline job
jobs:
  build-and-push:
    runs-on: ubuntu-latest

#Repository kód letöltése
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

#Docker Hub bejelentkezés
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

#Docker image buildelése és pusholása a Docker Hub-ra
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: kn5yjf/hello-devops:v1